# nginx Web Server

# does not work, test only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knife
  namespace: student-c-aberger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["tail", "-f", "/dev/null"]
        workingDir: /root  
        volumeMounts:
        - name: html
          mountPath: /srv
          readOnly: false
        - name: setup-script
          mountPath: /usr/local/bin
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nginx-www
        - name: setup-script
          configMap:
            name: download-webcontent
            defaultMode: 0744
            items:
              - key: download-webcontent.sh
                path: download-webcontent.sh


